Sob 42 add component slider
vorobeybird/Sobesity-UI pull request #16
Opened 2022-12-09 14:17 UTC by vorobeybird

2022-12-11 20:28 UTC, vorobeybird commented
![image](https://user-images.githubusercontent.com/46844648/206927144-b0fc95e9-1339-46ec-ae4d-c231ad26bae1.png)

2022-12-12 15:40 UTC, HardKullez requested changes

2022-12-12 15:40 UTC, HardKullez commented on src/index.css
> +}
Не могу решить имеет ли это отношение к непосредственно реализации слайдера, но обязательно `pointer-events: none;` надо будет добавлять к картинкам в текущей реализации, иначе drag на картинку нативный браузерный срабатывает, а не на слайдер

2022-12-12 15:40 UTC, HardKullez commented on src/components/carousel/carousel.tsx
> +                <div
Тут key забыл добавить

2022-12-12 15:40 UTC, HardKullez commented on src/components/carousel/carousel.tsx
> +  children: PropTypes.element,
Тут наверно PropTypes.node нужен, там не компонент пробрасывается. С PropTypes.element в рантайме ворн 
![image](https://user-images.githubusercontent.com/62354609/207085375-7bc2d58b-b8df-4b72-b85b-719b15606e5d.png)

2022-12-13 07:46 UTC, Slanx commented on src/components/carousel/use-carousel.ts
> +    case 'drag':
Енам экспортирован, кейсы можно через него подставлять.

2022-12-13 07:46 UTC, Slanx commented on src/components/carousel/use-carousel.ts
> +}
Эту всю функцию можно типизировать.
В react-swipeble есть тип для ивентов, тогда нужно будеть подправить типы в функции на 24 строке.
dispatch Можно типизировать через React.Dispatch т.к. используется UseReducer, и кроме того у тебя в экшены Next и Prev не всегда передаётся атрибут disered, значит его можно сделать необязательным. Ну либо передавать его в аргументы этой функции.

2022-12-13 07:46 UTC, Slanx commented on src/index.css
> +}
Даже если имеет, использовать Css нет смысла, можно все сделать через конфиг Tailwind.  Кроме того класс контейнера, тоже прописан в документации TW.

2022-12-13 08:07 UTC, Slanx commented on src/components/carousel/carousel.types.ts
> +}
Судя по редюсеру в UseCarousel, у тебя атрибут desired, не используется в экшенах, а высчитывается. Поэтому в dispatch нет смысла его передавать

2022-12-13 08:47 UTC, vorobeybird commented on src/components/carousel/carousel.tsx
> +          <div>
Fixed

2022-12-13 09:59 UTC, vorobeybird commented on src/components/carousel/carousel.tsx
> +                <div
fixed

2022-12-13 10:40 UTC, vorobeybird commented on src/components/carousel/carousel.types.ts
> +}
fixed

2022-12-13 10:42 UTC, vorobeybird commented on src/components/carousel/carousel.tsx
> +              })}
fixed

2022-12-13 11:18 UTC, vorobeybird commented on src/components/carousel/use-carousel.ts
> +}
fixed

2022-12-13 11:22 UTC, vorobeybird commented on src/components/carousel/use-carousel.ts
> +    case 'drag':
fixed

2022-12-13 11:43 UTC, merged