SOB-61 feat: landing  create screening component
vorobeybird/Sobesity-UI pull request #29
Opened 2023-01-11 20:20 UTC by pavelgre4a

![image](https://user-images.githubusercontent.com/103334312/211909242-efce32fa-edcd-4636-b531-bbc7d078d3a0.png)

Вот эту штуку ниже не стал делать, мне кажется её лучше сделать отдельным компонентом или запихнуть отдельным блоком в обёртку
![image](https://user-images.githubusercontent.com/103334312/211909403-56161559-90e2-4282-944c-015fa804544a.png)

2023-01-11 20:21 UTC, pavelgre4a commented
![](https://github.trello.services/images/mini-trello-icon.png) [Landing Second Section tiles](https://trello.com/c/vugUYmxO/61-landing-second-section-tiles)

2023-01-12 00:03 UTC, HardKullez commented
Как-то не очень нравится использование className + classNames одновременно, когда это не для тогда состояний класса по типу classname: condition
Это нормально или тавтология бессмысленная получается? @vorobeybird @Slanx 
![image](https://user-images.githubusercontent.com/62354609/211944218-070dc820-884f-4464-a551-a9ffb9362673.png)

2023-01-12 06:55 UTC, pavelgre4a commented
Там же будут ещё стили для lg, поэтому это с заделом на будущее в моем понимании

2023-01-13 07:47 UTC, vorobeybird requested changes

2023-01-16 08:02 UTC, merged